apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    build.appstudio.openshift.io/application: application-to-test-git-ops
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: java-quarkus-12
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: appstudio
  namespace: sbudhwar-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
status: {}
